// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type DocsInstance struct {
	ID        int32  `json:"id"`
	OwnerId   int32  `json:"ownerId"`
	Name      string `json:"name"`
	Public    bool   `json:"public"`
	RepoOwner string `json:"repoOwner"`
	RepoName  string `json:"repoName"`
	RepoRef   string `json:"repoRef"`
	Root      string `json:"root"`
}

type MailAccount struct {
	ID       int32  `json:"id"`
	OwnerId  int32  `json:"ownerId"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}
