// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	AddEmailAccount(ctx context.Context, arg AddEmailAccountParams) (int32, error)
	AddSession(ctx context.Context, arg AddSessionParams) (*UserSession, error)
	AddShare(ctx context.Context, arg AddShareParams) error
	AddUser(ctx context.Context, arg AddUserParams) (*User, error)
	ClearUserSessions(ctx context.Context, userid int32) error
	CountUserMailAccounts(ctx context.Context, ownerid int32) (int64, error)
	DeleteMailAccount(ctx context.Context, id int32) error
	DeleteSessionByHash(ctx context.Context, tokenhash string) error
	DeleteSessionById(ctx context.Context, userId int32, iD int32) error
	DeleteShare(ctx context.Context, userId int32, account int32) error
	GetMailAccountByEmail(ctx context.Context, email string) (*MailAccount, error)
	GetMailAccountById(ctx context.Context, id int32) (*MailAccount, error)
	GetSessionFromHash(ctx context.Context, tokenhash string) (*UserSession, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserById(ctx context.Context, id int32) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	GetUserSessions(ctx context.Context, userid int32) ([]*UserSession, error)
	ListAccountShares(ctx context.Context, account int32) ([]int32, error)
	ListUserMailAccounts(ctx context.Context, ownerid int32) ([]*MailAccount, error)
	ListUserNames(ctx context.Context) ([]string, error)
	ListUsers(ctx context.Context, limit int32, offset int32) ([]*User, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) error
}

var _ Querier = (*Queries)(nil)
